name: Vote → IFTTT auto-post (2x daily)

on:
  workflow_dispatch:  # GASからだけ起動

permissions:
  contents: write     # 画像をコミット/プッシュするため

concurrency:
  group: sugushinu-daily
  cancel-in-progress: true

env:
  TZ: Asia/Tokyo
  TOP_N: "5"

jobs:
  run-post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Japanese fonts (Noto CJK)
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml matplotlib numpy

      - name: Decide RUN_LABEL by JST hour (AM/PM)
        run: |
          HOUR=$(TZ=Asia/Tokyo date +%H)
          if [ "$HOUR" -lt 12 ]; then LABEL=AM; else LABEL=PM; fi
          echo "RUN_LABEL=$LABEL" >> "$GITHUB_ENV"
          echo "RUN_LABEL=$LABEL"

      - name: Run script (scrape & draw & tweet via IFTTT)
        env:
          IFTTT_KEY: ${{ secrets.IFTTT_KEY }}
          IFTTT_EVENT: ${{ secrets.IFTTT_EVENT }}
        run: |
          python scrape_and_publish.py

      - name: List public dir (debug)
        if: always()
        run: |
          ls -lah public || true
