name: Vote → IFTTT auto-post

on:
  workflow_dispatch: {}   # ← GAS から起動

permissions:
  contents: write

concurrency:
  group: vote-ifttt
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps (minimal)
        run: |
          pip install --upgrade pip
          pip install requests beautifulsoup4 matplotlib lxml pillow

      # 実行時のJSTで AM/PM を判定
      - name: Set RUN_LABEL by JST hour
        run: |
          export TZ=Asia/Tokyo
          h=$(date +%H)
          if [ "$h" = "08" ]; then
            echo "RUN_LABEL=AM" >> $GITHUB_ENV
          elif [ "$h" = "20" ]; then
            echo "RUN_LABEL=PM" >> $GITHUB_ENV
          else
            echo "RUN_LABEL=" >> $GITHUB_ENV

      - name: Scrape → Image → Commit → IFTTT
        env:
          TOP_N: "5"
          IFTTT_KEY: ${{ secrets.IFTTT_KEY }}
          IFTTT_EVENT: ${{ secrets.IFTTT_EVENT }}
          RUN_LABEL: ${{ env.RUN_LABEL }}
        run: |
          python scrape_and_publish.py
