name: Vote → IFTTT auto-post (2x daily)

on:
  schedule:
    - cron: "0 23 * * *"  # JST 08:00
    - cron: "0 11 * * *"  # JST 20:00
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: sudo apt-get update && sudo apt-get install -y fonts-noto-cjk
      - run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install requests beautifulsoup4 matplotlib lxml pillow
          fi
      - name: AM run vars
        if: ${{ github.event.schedule == '0 23 * * *' }}
        run: echo "RUN_LABEL=AM" >> $GITHUB_ENV
      - name: PM run vars
        if: ${{ github.event.schedule == '0 11 * * *' }}
        run: echo "RUN_LABEL=PM" >> $GITHUB_ENV
      - name: Scrape → Image → Commit → IFTTT
        env:
          TOP_N: "5"
          IFTTT_KEY: ${{ secrets.IFTTT_KEY }}
          IFTTT_EVENT: ${{ secrets.IFTTT_EVENT }}
          RUN_LABEL: ${{ env.RUN_LABEL }}
        run: python scrape_and_publish.py
